#!/bin/zsh

set -e

REPODIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ; cd .. )"
REPODIR="$(dirname "$REPODIR")"

echo ">> Copying $HOME/.config/skhd"
cp -r $HOME/.config/skhd $REPODIR/config/
echo ">> Copying $HOME/.config/yabai"
cp -r $HOME/.config/yabai $REPODIR/config/

cd $REPODIR
git pull
git add .
git commit -m "updating config files from system"
git push

cd -

exit 0

