#!/bin/zsh

IDEA=`ls -1d /Applications/IntelliJ* | tail -n1`

if [ -z "$IDEA" ]; then
  IDEA=`ls -1d $HOME/Applications/IntelliJ* | tail -n1`
  if [ -z "$IDEA" ]; then
    echo "IntelliJ not found"
    exit 1
  fi
fi

echo "Found IDEA: $IDEA"

wd=`pwd`

if [ -d "$1" ]; then
    echo "checking for things in the working dir given"
    wd=$(ls -1d "$1" | head -n1)
fi

if [ -f "$1" ]; then
    echo "opening '$1'"
    open -a "$IDEA" "$1"
else
    pushd "$wd" > /dev/null

    if [ -d ".idea" ]; then
        echo "opening via the .idea dir"
        open -a "$IDEA" .

    elif [ -f \*.ipr ]; then
        echo "opening via the project file"
        open -a "$IDEA" $(ls -1d *.ipr | head -n1)

    elif [ -f pom.xml ]; then
        echo "importing from pom"
        open -a "$IDEA" "pom.xml"

    elif [ -f build.sbt ]; then
        echo "importing scala project from build.sbt"
        open -a "$IDEA" "build.sbt"

    elif [ -f project.clj ]; then
        echo "importing clojure project from project.clj"
        open -a "$IDEA" "project.clj"

    elif [ -f Setup.hs ]; then
        echo "importing haskell project from Setup.hs"
        open -a "$IDEA" "Setup.hs"

    else
        open -a "$IDEA" "$1"
    fi

    popd > /dev/null
fi
