#!/bin/zsh

####### define script global variables here #######
# get absolute directory of this script
BASEDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"


####### put environment variables here #######
export NVM_DIR=~/.nvm
export SDKMAN_DIR="$HOME/.sdkman"


####### load scripts here #######

# Node
source $(brew --prefix nvm)/nvm.sh
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Python
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Ruby
export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


####### define aliases here #######

alias processOnPort='pp(){ sudo lsof -nP -iTCP:$1 | grep LISTEN}; pp'
alias idea='${BASEDIR}/idea $1'
alias sqlworkbenchj='java -jar /Applications/sqlworkbench.jar &'
alias g='git'
alias 101='one(){ cd $HOME/sources/private/101s && ./101 $1 $2 && cd -}; one'
alias v='nvim'
