#!/bin/zsh

####### define script global variables here #######
# get absolute directory of this script
BASEDIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"


####### put environment variables here #######
export NVM_DIR=~/.nvm
export SDKMAN_DIR="$HOME/.sdkman"


####### load scripts here #######
source $(brew --prefix nvm)/nvm.sh
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

####### define aliases here #######
alias processOnPort='pp(){ sudo lsof -nP -iTCP:$1 | grep LISTEN}; pp'
alias idea='${BASEDIR}/idea $1'
alias sqlworkbenchj='java -jar /Applications/sqlworkbench.jar &'
alias g='git'
